#!/bin/bash

function add {

	if [[ ${#argArray[@]} -eq 0 ]];then
		printf "Add: No arguments provided\n"
		exit 0
	fi

	if [[ -v "argArray[all]" ]]; then
		toCopy=*
	elif [[ -v "argArray[file]" ]]; then
		toCopy=${argArray[file]}
		if [[ ! -f $toCopy ]]; then
			echo "Add: File '${argArray[file]}' doesn't exist"
			exit 0
		fi
	else
		echo "Add: No file provided"
		exit 0
	fi


	if [[ ! -d '.staging' ]]; then
		mkdir './.staging'
	fi
	cp -r $toCopy ./.staging/

	if [[ -v "argArray[all]" ]];then
		printf "All files in directory added to staging\n"
	else
		printf "$toCopy added to staging\n"
	fi
}

function listStaging {

	printf "Files in staging \n"	
	printf "\n"
	unset fileDir
	if [[ -d './.staging' ]]; then
		index=0
		files=($(ls ./.staging))
		for line in ${files[@]}; do
			printf "\t- $index: $line\n"
			fileDir[index]=".staging/$line"
			(( index = index+1 ))
		done
	else
		printf "\tNo files in staging\n"
	fi	
	printf "\n"
}

function listLastCommit {
	printf "Files in last commit \n"	
	printf "\n"
	if [[ -d './.commit' ]]; then
		commits=($(ls .commit/ | sort -r))
		if [[ ! -z $commits ]];then
			files=($(ls .commit/${commits[0]}/))		
			index=0
			unset fileDir
			printf "Files in last commit '${commits[0]}':\n"
			for line in ${files[@]}; do
				printf "\t- $index: $line\n"
				fileDir[index]=".commit/${commits[0]}/$line"
				(( index = index+1 ))
			done
		else
			printf "\tNo files in commit\n"
		fi
	else
		printf "\tNo files in commit\n"
	fi
	printf "\n"

}

function listCommits {
	printf "Files in commit \n"	
	printf "\n"
	if [[ -d './.commit' ]]; then
		commits=($(ls .commit/ | sort -r))
		if [[ ! -z $commits ]]; then
			printf "Select a commit to view: \n"
			unset fileDir
			index=1
			for commit in ${commits[@]}; do
				printf "\t$index: $commit\n"
				(( index = index+1 ))
			done
			read -p "Enter option: " userAction
			printf "\n"
			choice=$(( $userAction-1 ))
			files=($(ls .commit/${commits[$choice]}))
			index=0
			cat .commit/${commits[$choice]}/.commitInfo
			printf "Files in commit: '${commits[$choice]}'\n"
			for file in ${files[@]}; do
				printf "\t- $index: $file\n"
				fileDir[index]=".commit/${commits[$choice]}/$file"
				(( index = index +1 ))
			done
			printf "\n"
		else
			printf "\tNo files in commit\n"
		fi
	else
		printf "\tNo files in commit\n"
	fi

}


function list {
	if test ${#argArray[@]}  -gt 0; then
		for arg in ${!argArray[@]}; do
			case $arg in
				staging) listStaging ;;
				last) listLastCommit ;;
				commits) listCommits ;;
			esac
			printf "****\n"
		done
	else	
		printf "\n"
		exit=false
		while [[ $exit = false ]]; do
			printf "List files: Please select an option\n\t1: files in staging\n\t2: files in the last commit\n\t3: files in an older commit\n\t4: exit \nOption:  "
			read userAction
			printf "\n"
			case $userAction in
				"1") 
					listStaging	
					;;
				"2")
					listLastCommit
					;;
				"3")
					listCommits
					;;
				"4")
					exit=true
					;;	
				"*")
					printf "Wrong action entered\n"
					;;
			esac
		done
	fi
}

function commit {
#	echo 'commit function'
	
	if [[ ${#argArray[@]} -eq 0 ]];then
		printf "Commit: no arguments provided\n"
		exit 0
	fi

	if [[ ! -d ./.staging ]]; then
		echo "No files in staging"
		exit 0
	fi

	if [[ -z "$(ls -A ./.staging/)" ]]; then
		echo "No files in staging"
		exit 0
	fi
	
	if [[ ${!argArray[@]} != 'msg' ]]; then
		echo "Commit: no message provided"
		exit 0
	fi
	
	commitDate=$(date)
	mkdir -p ./.commit
	commitDirs=($(ls ./.commit))
		
	lastCommit=0
	for commit in ${commitDirs[@]}; do

		result=$(cleanup $commit)
		if [[ $result == 'ready' ]]; then
			dir=${commit:1}
			if [[ $dir -gt $lastCommit ]]; then
				#echo "last commit $lastCommit dir $dir"
				lastCommit=$dir
			fi
		fi
	done

	if [[ $lastCommit -ne 0 ]]; then
#		echo "last commit found"
		commitNum=$(($lastCommit +1))
		commitName="c$commitNum"
		mkdir -p ./.commit/$commitName
		cp -r .commit/c$lastCommit/. ./.commit/$commitName/
	else
		commitName="c1"
		mkdir -p ./.commit/$commitName/
	fi
	
	stagingfiles=($(ls .staging))
	commitfiles=($(ls .commit/$commitName))
	echo "incomplete" > ./.commit/$commitName/.commitInfo
	
	printf "Creating new commit: $commitName \n"
	printf "Staged files: \n"
	for file in ${stagingfiles[@]};
	do
		printf "\t$file\n"
	done
	printf "\n"
	
	for file in ${stagingfiles[@]}
	do
		if [[ -f .commit/$commitName/$file ]]; then
			merge $file $commitName
		else		
			cp .staging/$file .commit/$commitName/
			printf "\t$file added to commit\n"
		fi
	done

	echo "Commit date: "$commitDate > ./.commit/$commitName/.commitInfo
	echo "Message: "${argArray[0]} >> ./.commit/$commitName/.commitInfo
	#chmod 444 ./.commit/$commitName/
	rm -r ./.staging
	echo "Commit complete"
}

function cleanup {

	status=($(cat ./.commit/$1/.commitInfo))
	if [[ ${status[0]} == 'incomplete' ]]; then
		rm -r .commit/$1
		echo 'incomplete'
	else
		echo 'ready'
	fi

}

function merge {
	
	printf "File '$1' exists in last commit "
	compare=$(diff -q .staging/$1 .commit/$2/$1)
	if [[ $compare == "" ]]; then
		echo "and the files are identical"
	else
		echo "but the files are not identical"
	fi

	mergeComplete="false"
	while [[ $mergeComplete != true ]]; do
		printf "Do you want to overwrite (1) or merge (2) '$1' ? "
		read userAction

		case $userAction in
			"1")
				cp .staging/$1 .commit/$2/$1
				mergeComplete=true
				echo "File $1 overwritten"
				;;
			"2")
				printf "Merging $1\n"
				printf "\n"
				# create a copy of the staging file
				# process will iteratively align the commit file and the staging file until there
				# are no differences left between the two
				cp .staging/$1 .commit/$2/.$1.merging
				compare=$(diff -q .commit/$2/.$1.merging .commit/$2/$1)
				while [[ $compare != ""  ]]; do
					diff ".commit/$2/$1" ".commit/$2/.$1.merging" | awk -f awkdiff
					mergeAction=$(sed "1q;d" .commit/.action.merge)
					blockMerge $1 $2 $mergeAction 
					compare=$(diff -q .commit/$2/.$1.merging .commit/$2/$1)
					rm -f ./.commit/.action.merge
					rm -f ./.commit/.start.merge
					rm -f ./.commit/.finish.merge
					rm -f ./.commit/.add.merge
					rm -f ./.commit/.remove.merge
					rm -f ./.commit/.display.merge
				done
 				rm -f .commit/$2/.$1.merging
				mergeComplete=true
				echo "Merge complete"
				;;
			*)
				echo 'Wrong action entered'
				;;
		esac
	done
}


function blockMerge {
	case $3 in 
		"a")
			finishLocs=($(sed -n "1,2p" .commit/.finish.merge))

			printf "Do you want to add the following lines at line(s): ${finishLocs[0]}-${finishLocs[1]} (Y/n) ?\n "
			printf "\n"
			cat .commit/.display.merge 
		 	printf "\n"
			
			read -p "Enter (Y/n): " userAction
			case $userAction in
				[Yy])
			
					lines=($(wc -l .commit/$2/$1))
					if test ${lines[0]} -lt ${finishLocs[0]}; then
						cat .commit/.add.merge >> .commit/$2/$1
					else			
						cat .commit/.add.merge | sed -i ${finishLocs[0]}'e cat /dev/stdin' .commit/$2/$1
					fi
					;;
				[Nn])
					loc=${finishLocs[0]}","${finishLocs[1]}"d"
					sed -i $loc .commit/$2/.$1.merging
					;;
			esac

			;;
		"c")

			startLocs=($(sed -n "1,2p" .commit/.start.merge))
			finishLocs=($(sed -n "1,2p" .commit/.finish.merge))	
		
			printf "Do you want to replace the following lines at line(s): ${startLocs[0]}-${startLocs[1]} (Y/n) ?\n "
			printf "\n"
			cat .commit/.display.merge
			printf "\n"
		
			read -p "Enter (Y/n): " userAction
			case $userAction in 
				[Yy])
					
					sed -i "${startLocs[0]},${startLocs[1]}d" .commit/$2/$1
					lines=($(wc -l .commit/$2/$1))
					if test ${lines[0]} -lt ${finishLocs[0]}; then
						cat .commit/.add.merge >> .commit/$2/$1
					else			
						cat .commit/.add.merge | sed -i ${finishLocs[0]}'e cat /dev/stdin' .commit/$2/$1
					fi
					;;
				[Nn])
					sed -i "${finishLocs[0]},${finishLocs[1]}d" .commit/$2/.$1.merging
					lines=($(wc -l .commit/$2/.$1.merging))
					if test ${lines[0]} -lt ${startLocs[0]}; then
						cat .commit/.remove.merge >> .commit/$2/.$1.merging
					else			
						cat .commit/.remove.merge | sed -i ${startLocs[0]}'e cat /dev/stdin' .commit/$2/.$1.merging
					fi
					;;
			esac
			;;
		"d")
			startLocs=($(sed -n "1,2p" .commit/.start.merge))
			finishLocs=($(sed -n "1,2p" .commit/.finish.merge))	
			printf "Do you want to delete the following lines at line(s): ${startLocs[0]}-${startLocs[1]} (Y/n) ?\n "
			printf "\n"
			cat .commit/.display.merge
			printf "\n"
		
			read -p "Enter (Y/n): " userAction
			case $userAction in 
				[Yy])
					sed -i "${startLocs[0]},${startLocs[1]}d" .commit/$2/$1
					;;
				[Nn])
					lines=($(wc -l .commit/$2/.$1.merging))
					if test ${lines[0]} -lt ${startLocs[0]}; then
						cat .commit/.remove.merge >> .commit/$2/.$1.merging
					else			
						cat .commit/.remove.merge | sed -i ${startLocs[0]}'e cat /dev/stdin' .commit/$2/.$1.merging
					fi
					;;
			esac
			;;
			
			
	esac

}

function display {

	if test ${#argArray[@]} -eq 1; then
		case ${!argArray[@]} in
			staging) listStaging ;;
			last) listLastCommit ;;
			commits) listCommits;;
		esac
	      	read -p "Please enter a file number to view file: " userAction
		length=($(wc -l ${fileDir[$userAction]}))
		if [[ ${length[0]} -lt 30 ]]; then
			increment=${length[0]}
		else
			increment=30
		fi
		printf "Printing file: ${fileDir[$userAction]}\n"
		printf "Press any key to cycle through pages\n"
		printf "Number of lines in file: ${length[0]}\n"
		for (( i=1 ; i <= ${length[0]};i=$(($i+$increment)) )); do
			end=$(($i+$increment))
			cat ${fileDir[$userAction]} | awk 'NR >='$i' && NR <'$end' {print NR":",$0}'
			read 	
		done

	else
		if test ${#argArray[@]} -eq 0; then
			printf "Please specify a flag for the display function:\n\t-s (staging folder)\n\t-l (last commit folder)\n\t-c (choose commit)\n"
		elif	test ${#argArray[@]} -gt 1; then
			printf "Please only specify one flag for this function\n"
		fi
	fi	
}

function man {
	printf "vc help\n
Usage: vc [COMMAND] [OPTION]
	Description: Version control your files with vc

Command: vc add
	Description: Add files to staging area
	Usage:
		vc add -f FILE (add a specific file)
		vc add -a (add all files in directory)

Command: vc list
	Description: List all files in relevant folders
	Usage:
		vc list 	(user is given an interactive display)
		vc list -s 	(list all files in staging)
		vc list -l 	(list all files in the last commit)
		vc list -c 	(choose which commit to view)
	
Command: vc commit
	Description: Add all files in staging to a commit. If there are
		differences between files, a merge procedure will be initiated.
	Usage:
		vc commit -m MESSAGE (Commit all files with a commit message)

Command: vc display
	Description: Display paginated contents of staged and committed files 
		in the repository
	Usage:
		vc display -s 	(choose a file to view from staging)
		vc display -l 	(choose a file to view from the last commit)
		vc display -c 	(choose a file to view from any commit)


	"
}


if [[ $# -eq 0 ]];
then
	printf "No parameters provided\n\n"
	printf "Enter vc help for details\n"
	exit 0
fi

case $1 in
	"add"|"list"|"commit"|"display"|"help")
		action=$1
		shift
		;;
	*)
		printf "No command provided\nPlease enter 'vc help' for more information\n"
		exit
		;;
esac

declare -a fileDir
declare -A argArray

if [ $action == 'add' ]; then

	while getopts 'af:' flag; do
		case $flag in
			a)
				argArray[all]=true 
				if [[ -v "argArray[file]" ]]; then
					unset $argArray[file]
				fi
				break
				;;
				
			f) 
				argArray[file]=${OPTARG} ;;
		esac
	done
	add 
	
elif [ $action == 'list' ]; then
	
	while getopts 'slc' flag; do
		case $flag in
			s) argArray[staging]=true ;;
			l) argArray[last]=true ;;
			c) argArray[commits]=true ;;
		esac
	done
	list

elif [ $action == 'commit' ]; then
	
	while getopts 'm:' flag; do
		case $flag in
			m) argArray[msg]=${OPTARG} ;;
		esac
	done
	commit 

elif [ $action == 'display' ]; then
	
	while getopts 'slc' flag; do
		case $flag in
			s) argArray[staging]=true ;;
			l) argArray[last]=true ;;
			c) argArray[commits]=true ;;
		esac
	done
	display

elif [ $action == 'help' ]; then
	man
fi


